name = "Aiban Modpack"
author = "Firo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b932b8b812a36e0cd460c892efe897d74f6ef0e68c79b2debde83495f756d1a4"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
