name = "Aiban Modpack"
author = "Firo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8145c915e19128f1602e737d7d36c69d18ae008ec256b289c23fdf5c7dffa2e9"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
